dist: trusty
sudo: required
group: deprecated-2017Q2

# lib contains jar files to support running tests
cache:
  directories:
    - lib

  # We only are going to test on jdk8 + jdk10.
  # openjdk9 + oraclejdk10 were both removed from Ubuntu

# Mainly for jdk11
language: java
jdk:
  - openjdk11
  - openjdk13

#matrix:
#  allow_failures:
#    - jdk: oraclejdk9

# Currently oraclejdk8 is mapped to DB=mysql and the
# others are DB=postgres.
#
# a test env of: - DB=mysql  TEST=tatp
# duplicated for postgres would of been nice however
# attempting to limit non-junit tests to single jdk with
# matrix:
#   exclude:
#     - jdk: oraclejdk8
#       env: DB=mysql
#     - jdk: oraclejdk9
#       env: DB=mysql
#     - jdk: oraclejdk8
#       env: DB=postgres
#     - jdk: oraclejdk9
#       env: DB=postgres
# Failed to exclude any elements.

# Possibilities for future:
# matrix:
#   include:
#    - addons:
#      mariadb: 5.5
#    - addons:
#      mariadb: 10.0
#    - addons:
#      mariadb: 10.1
#    - addons:
#      mariadb: 10.2
#    - addons:
#      postgresql: 9.4
#    - addons:
#      postgresql: 9.5
#    - addons:
#      postgresql: 9.6
##    - addons:
##      postgresql: 9.7
# https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version
# MariaDB wasn't supported on trusty-containers at time of writing
# This syntax may not be correct.


addons:
  postgresql: 9.6

env:
  - TEST=junit
  - TEST=epinions
  - TEST=tatp
  - TEST=tpcc
  - TEST=voter
  - TEST=auctionmark
  - TEST=wikipedia
  - TEST=ycsb
  - TEST=seats
  - TEST=sibench
  - TEST=noop
  - TEST=smallbank
  - TEST=twitter
  - TEST=resourcestresser
  - TEST=chbenchmark

# Missing loader com.oltpbenchmark.benchmarks.resourcestresser.ResourceStresserBenchmark.makeLoaderImpl(ResourceStresserBenchmark.java:58)
# -> org.apache.commons.lang.NotImplementedException: Code is not implemented
#  - TEST=resourcestresser

# Missing sample config file
#  - TEST=chbenchmark
#
# Missing sample config
#  - TEST=hyadapt
#
# Not fully implemented
#  - TEST=jpab
#
# Works only for MySQL at this time
#  - TEST=linkbench
#

# While mariadb addon isn't used. Remove if using a addon: mariadb

services:
  - mysql
  - postgresql

# Increase the size of ramdisk on sudo enabled infrastructure
# https://github.com/travis-ci/travis-ci/issues/9036#issuecomment-357189213
before_install:
  - sudo mount -o remount,size=50% /var/ramfs

install:
  - echo $TRAVIS_JDK_VERSION
  - if [ $TRAVIS_JDK_VERSION == openjdk13 ]; then
    DB=postgres;
    else
    DB=mysql;
    fi
  - if [ $DB == mysql ]; then mysql -e "SELECT VERSION()";
    echo -e "[mysqld]\nlower_case_table_names=1" | sudo tee -a /etc/mysql/my.cnf ;
    sudo service mysql restart ;
    mysql -e "CREATE DATABASE IF NOT EXISTS ${TEST}" ;
    mysql -e "DROP USER 'travis'@'localhost'" ;
    mysql -e "flush privileges" ;
    mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis'; GRANT ALL ON *.* TO 'travis'@'localhost'";
    elif [ $DB == postgres ]; then psql -c "SELECT VERSION()" -U travis;
    sudo service postgresql restart ;
    psql -c "create database $TEST" -U postgres ;
    psql -c "ALTER USER CURRENT_USER WITH PASSWORD 'travis'" -U travis;
    fi

# MySQL create user is probably one of the trust-container bugs for MySQL
# Will probably need the following to set a password

# We pass a password here as <password></password> sends no password in the protocol
# rather than the blank one and therefore fails on MySQL.

before_script:
  - if [ $DB == mysql ]; then
    URLBASE=jdbc:mysql://localhost:3306 ;
    DRIVER=com.mysql.jdbc.Driver ;
    TYPE=MYSQL ;
    elif [ $DB == postgres ]; then
    URLBASE=jdbc:postgresql://localhost:5432 ;
    DRIVER=org.postgresql.Driver ;
    TYPE=POSTGRES ;
    fi

script:
  - SCALEFACTOR=1
  - TIME=60
  - TERMINALS=1
  - if [ $TEST == chbenchmark ]; then
    BENCH=${TEST},tpcc ;
    else
    BENCH=${TEST} ;
    fi
  - ./mvnw clean package;
  - if [ $TEST == junit ]; then
    mvn test;
    else
    cd target;
    unzip oltpbench2-20.1.3-SNAPSHOT.zip;
    cd oltpbench2-20.1.3-SNAPSHOT;
    config=config/${DB}/sample_${TEST}_config.xml ;
    sed -i
    -e "/<type>/c\<type>${TYPE}</type>"
    -e "/<driver>/c\<driver>${DRIVER}</driver>"
    -e "/<url>/c\<url>${URLBASE}/${TEST}</url>"
    -e "/<username>/c\<username>travis</username>"
    -e "/<password>/c\<password>travis</password>"
    -e "/<isolation>/c\<isolation>TRANSACTION_SERIALIZABLE</isolation>"
    -e "/<batchsize>/c\<batchsize>128</batchsize>"
    -e "/<scalefactor>/c\<scalefactor>${SCALEFACTOR}</scalefactor>"
    -e "/<terminals>/c\<terminals>${TERMINALS}</terminals>"
    -e "/<time>/c\<time>${TIME}</time>"
    "${config}";
    java -jar oltpbench2.jar -b "${BENCH}" -c "${config}" --create=true --load=true --execute=true;
    fi

# With tests, scalefactor and terminals are just to reduce load on travis
# isolation READ_COMMITTED as the TRANSACTIONAL default caused too many failures for now.

after_script:
  - if [ $DB == mysql ]; then
    mysql -e "DROP DATABASE IF EXISTS ${TEST}" ;
    elif [ $DB == postgres ]; then
    psql -c "DROP DATABASE IF EXISTS ${TEST}" -U postgres ;
    fi
